name: CICD

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-northeast-2
      ECR_REGISTRY: 277707114689.dkr.ecr.ap-northeast-2.amazonaws.com
      IMAGE_NAME: tama-api/order
      CLUSTER_NAME: tama-api-cluster

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Create gradle.properties
        run: |
          mkdir -p ~/.gradle
          echo "${{ secrets.GRADLE_PROPERTIES }}" > ~/.gradle/gradle.properties

      - name: Enable Docker BuildKit
        run: |
          echo "DOCKER_BUILDKIT=1" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build \
            --secret id=gradle_properties,src=$HOME/.gradle/gradle.properties \
            -t $IMAGE_NAME .

      - name: Tag SHA image
        run: |
          docker tag $IMAGE_NAME:latest \
          $ECR_REGISTRY/$IMAGE_NAME:${{ github.sha }}

      - name: Tag latest image
        run: |
          docker tag $IMAGE_NAME:latest \
          $ECR_REGISTRY/$IMAGE_NAME:latest

      - name: Push SHA image
        run: |
          docker push \
          $ECR_REGISTRY/$IMAGE_NAME:${{ github.sha }}

      - name: Push latest image
        run: |
          docker push \
          $ECR_REGISTRY/$IMAGE_NAME:latest
